### ISSUE TITLE
UsbCamera

### ISSUE THREAD

**Issue by Onafets51** [secile/UsbCamera#3]
I am using your work with satisfaction and I would like to know, since some cameras have a serial code, would it be possible to read it?

**Comment by secile** [comment]
Thank you for your question.
As long as I know, there is no common way to get device serial code in DirectShow.
Instead of that, it is possible to read DevicePath property.

[https://docs.microsoft.com/ja-jp/windows/win32/directshow/selecting-a-capture-device?redirectedfrom=MSDN](url)
> DevicePath property is not a human-readable string, but is guaranteed to be unique for each video capture device on the system. You can use this property to distinguish between two or more instances of the same model of device.

UsbCamera.FindDevices() currently returns array of USB camera name. To change returns array of USB camera 'DevicePath', change line 686 as below.

```C#
prop.Read("FriendlyName", ref value, 0);
```

to

```C#
prop.Read("DevicePath", ref value, 0);
```
